const swaggerAutoGen = require('swagger-autogen')();

const outputFile = './swagger_docs.json'
const doc = {
    info: {
        version: "1.0.0",
        title: "Kofi's Portfolio",
        description: "Documentation automatically generated by the <b>swagger-autogen</b> module for Kofi's Portfolio API."
    },
}

const endpointFiles = ['./routes/index.js'];

swaggerAutoGen(outputFile, endpointFiles, doc).then(()=>{
    require('./index');
})