const swaggerAutoGen = require('swagger-autogen')();

const outputFile = './swagger_docs.json'
const doc = {
    info: {
        version: "1.0.0",
        title: "Kofi's Portfolio",
        description: "Documentation automatically generated by the <b>swagger-autogen</b> module for Kofi's Portfolio API."
    },
    schemes: ['http', 'https'],
    tags: [
        {
            "name": "Education",
            "description": "All Education Endpoints"
        },
        {
            "name": "Experience",
            "description": "All Experience Endpoints"
        },
        {
            "name": "Projects",
            "description": "All Projects Endpoints"
        },
        {
            "name": "Resume",
            "description": "All Resume Endpoints"
        },
        {
            "name": "Tools",
            "description": "All Tools Endpoints"
        },
    ],
}

const endpointFiles = ['./routes/index.js'];

swaggerAutoGen(outputFile, endpointFiles, doc).then(()=>{
    require('./index');
})